services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    networks:
      - ragapp-network

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    command: [ "--config", "/app/config.yaml", "--debug" ]
    ports:
      - "4000:4000"
    volumes:
      - ./litellm.yaml:/app/config.yaml
    depends_on:
      - ollama
      - ddg-chat
    networks:
      - ragapp-network
    environment:
      - 'DUMMY_API_KEY=sk-1234'
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
      - 'DDG_CHAT_API_BASE_URL=http://ddg-chat:8787/v1'

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - ragapp-network

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 80:8080
    networks:
      - ragapp-network
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'

  ddg-chat:
    image: leafmoes/ddg-chat:latest
    container_name: ddg-chat
    ports:
      - "8787:8787"
    networks:
      - ragapp-network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8081:8080
    networks:
      - ragapp-network
    environment:
      - OLLAMA_BASE_URL="http://ollama:11434"

  setup:
    image: curlimages/curl:latest
    networks:
      - ragapp-network
    volumes:
      - ./scripts:/ragapp
    environment:
      - MODEL=${MODEL:-phi3:latest}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAMES=default
      - DISTANCE_METRIC=Cosine
      - VECTOR_SIZE=768
    command: >
      /bin/sh -c 
      "chmod +x /ragapp/create_qdrant_collection.sh /ragapp/setup_ollama.sh &&
      /ragapp/create_qdrant_collection.sh &&
      /ragapp/setup_ollama.sh"
    depends_on:
      - qdrant
      - ollama

  ragapp:
    build: src/ragapp
    image: ragapp/ragapp:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - VECTOR_STORE_PROVIDER=qdrant
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=default
      - QDRANT_API_KEY=""
      - MODEL_PROVIDER=ollama
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - EMBEDDING_MODEL=nomic-embed-text
      - EMBEDDING_DIM=768
      - MODEL=${MODEL:-phi3:latest}
      - TRACKING_SCRIPT=${TRACKING_SCRIPT:-}
    depends_on:
      - setup
    networks:
      - ragapp-network
  
networks:
  ragapp-network:
    name: ragapp-network
    # Set as an external network to avoid conflicts.
    external: true
