services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama-webui:/app/backend/data
    ports:
      - 80:8080
    environment:
      - OLLAMA_API_BASE_URL=http://10.78.26.223:11434/api

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./open-webui:/app/backend/data
    ports:
      - 8081:8080
    environment:
      - OLLAMA_BASE_URL=http://10.78.26.223:11434

  setup:
    image: curlimages/curl:latest
    volumes:
      - ./scripts:/ragapp
    environment:
      - MODEL=${MODEL:-phi3:latest}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://10.78.26.223:11434}
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAMES=default
      - DISTANCE_METRIC=Cosine
      - VECTOR_SIZE=768
    command: >
      /bin/sh -c 
      "chmod +x /ragapp/create_qdrant_collection.sh /ragapp/setup_ollama.sh &&
      /ragapp/create_qdrant_collection.sh &&
      /ragapp/setup_ollama.sh"

  ragapp:
    build: src/ragapp
    image: ragapp/ragapp:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - VECTOR_STORE_PROVIDER=qdrant
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=default
      - QDRANT_API_KEY=""
      - MODEL_PROVIDER=ollama
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://10.78.26.223:11434}
      - EMBEDDING_MODEL=nomic-embed-text
      - EMBEDDING_DIM=768
      - MODEL=${MODEL:-phi3:latest}
      - TRACKING_SCRIPT=${TRACKING_SCRIPT:-}
    depends_on:
      - setup
